# Generated by Django 2.2 on 2020-02-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_trade_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=200)),
                ('value_in_usd', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DerivataveTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_trade', models.DateField()),
                ('trade_id', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('buying_party', models.CharField(max_length=200)),
                ('selling_party', models.CharField(max_length=200)),
                ('notational_amount', models.FloatField()),
                ('quantity', models.FloatField()),
                ('notational_currency', models.CharField(max_length=200)),
                ('maturity_date', models.DateField()),
                ('underlying_price', models.FloatField()),
                ('underlying_currency', models.CharField(max_length=200)),
                ('strike_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=200)),
                ('market_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('company_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_id', models.CharField(max_length=200)),
                ('stock_price', models.FloatField()),
            ],
        ),
    ]
