# Generated by Django 3.0.2 on 2020-02-12 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivataveTradeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('added_to_report', models.BooleanField(default=False)),
                ('modified_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.DerivataveTrade')),
                ('originial_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='trades.DerivataveTrade')),
            ],
        ),
    ]
