# Generated by Django 3.0.2 on 2020-02-12 13:43

from django.db import migrations, models
import trades.models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_derivatavetradehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('report', models.FileField(upload_to=trades.models.Report.get_upload_path)),
            ],
            options={
                'ordering': ['-date_generated'],
            },
        ),
        migrations.AlterModelOptions(
            name='derivatavetrade',
            options={'ordering': ['-date_of_trade']},
        ),
        migrations.AlterModelOptions(
            name='derivatavetradehistory',
            options={'ordering': ['-date_modified']},
        ),
    ]
