# Generated by Django 3.0.2 on 2020-02-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DerivataveTrade',
            new_name='DerivativeTrade',
        ),
        migrations.RenameModel(
            old_name='DerivataveTradeHistory',
            new_name='DerivativeTradeHistory',
        ),
    ]
