# Generated by Django 3.0.2 on 2020-02-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivativetrade',
            name='trade_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
