# Generated by Django 3.0.2 on 2020-02-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20200213_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='date_generated',
            new_name='date',
        ),
    ]
