# Generated by Django 3.0.3 on 2020-03-05 13:56

from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('report', models.FileField(upload_to=report.models.Report.get_upload_path)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
