# Generated by Django 3.0.3 on 2020-03-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('report', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
